export const INITIAL_VALUE_RECIPE_MEAL = {
  dateModified: null,
  idMeal: ' ',
  strArea: ' ',
  strCategory: ' ',
  strCreativeCommonsConfirmed: null,
  strDrinkAlternate: null,
  strImageSource: null,
  strIngredient1: ' ',
  strIngredient2: ' ',
  strIngredient3: ' ',
  strIngredient4: ' ',
  strIngredient5: ' ',
  strIngredient6: ' ',
  strIngredient7: ' ',
  strIngredient8: ' ',
  strIngredient9: ' ',
  strIngredient10: ' ',
  strIngredient11: ' ',
  strIngredient12: ' ',
  strIngredient13: ' ',
  strIngredient14: ' ',
  strIngredient15: ' ',
  strIngredient16: ' ',
  strIngredient17: ' ',
  strIngredient18: ' ',
  strIngredient19: ' ',
  strIngredient20: ' ',
  strInstructions: ' ',
  strMeal: ' ',
  strMealThumb: ' ',
  strMeasure1: ' ',
  strMeasure2: ' ',
  strMeasure3: ' ',
  strMeasure4: ' ',
  strMeasure5: ' ',
  strMeasure6: ' ',
  strMeasure7: ' ',
  strMeasure8: ' ',
  strMeasure9: ' ',
  strMeasure10: ' ',
  strMeasure11: ' ',
  strMeasure12: ' ',
  strMeasure13: ' ',
  strMeasure14: ' ',
  strMeasure15: ' ',
  strMeasure16: ' ',
  strMeasure17: ' ',
  strMeasure18: ' ',
  strMeasure19: ' ',
  strMeasure20: ' ',
  strSource: ' ',
  strTags: ' ',
  strYoutube: ' ',
};

export const INITIAL_VALUE_RECIPE_DRINK = {
  dateModified: '',
  idDrink: '',
  strAlcoholic: '',
  strCategory: '',
  strCreativeCommonsConfirmed: '',
  strDrink: '',
  strDrinkAlternate: null,
  strDrinkThumb: '',
  strGlass: '',
  strIBA: null,
  strImageAttribution: null,
  strImageSource: null,
  strIngredient1: '',
  strIngredient2: '',
  strIngredient3: '',
  strIngredient4: null,
  strIngredient5: null,
  strIngredient6: null,
  strIngredient7: null,
  strIngredient8: null,
  strIngredient9: null,
  strIngredient10: null,
  strIngredient11: null,
  strIngredient12: null,
  strIngredient13: null,
  strIngredient14: null,
  strIngredient15: null,
  strInstructions: '',
  strInstructionsDE: '',
  strInstructionsES: null,
  strInstructionsFR: null,
  strInstructionsIT: '',
  strInstructionsZH_HANS: null,
  strInstructionsZH_HANT: null,
  strMeasure1: '',
  strMeasure2: null,
  strMeasure3: null,
  strMeasure4: null,
  strMeasure5: null,
  strMeasure6: null,
  strMeasure7: null,
  strMeasure8: null,
  strMeasure9: null,
  strMeasure10: null,
  strMeasure11: null,
  strMeasure12: null,
  strMeasure13: null,
  strMeasure14: null,
  strMeasure15: null,
  strTags: null,
  strVideo: null,
};
